#!/usr/bin/env python3
"""
gen_cv_pubs.py - emit the LaTeX Publications block from publications.json.

This is how publications.json drives the CV without a .bib. It prints
\\cvitemize2 items matching the existing resume style:
  - author names abbreviated to "F Last" (Zehao Xiao -> \\textbf{Z Xiao})
  - equal-contribution "*" marks preserved from the JSON author strings
  - a "(Equal contribution)" note auto-emitted when an entry has 2+ "*" marks,
    or a custom note taken from an optional per-entry "contrib" field
    (e.g. "Corresponding author")
  - venue+year as a linked tag

Paste the output into resume/Publications.tex, or have cc splice it between
markers:
    % PUBS-START (auto-generated by gen_cv_pubs.py — do not edit by hand)
    ...generated items...
    % PUBS-END

Usage: python3 gen_cv_pubs.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

ME = "Zehao Xiao"


def tex_escape(s):
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


def abbrev(name):
    """'Wenzhe Yin*' -> 'W Yin*'; already-short 'C Wang' -> 'C Wang'."""
    name = name.strip()
    star = ""
    if name.endswith("*"):
        star, name = "*", name[:-1].strip()
    toks = name.split()
    if len(toks) <= 1:
        return name + star
    return f"{toks[0][0].upper()} {toks[-1]}{star}"


def render_authors(authors):
    parts = []
    for a in authors.split(","):
        a = a.strip()
        if not a:
            continue
        short = abbrev(a)
        if a.replace("*", "").strip() == ME:
            short = f"\\textbf{{{short}}}"
        parts.append(short)
    return ", ".join(parts)


def contrib_note(p):
    if p.get("contrib"):
        return p["contrib"]
    if p.get("authors", "").count("*") >= 2:
        return "Equal contribution"
    return ""


def main():
    with open(os.path.join(HERE, "publications.json"), encoding="utf-8") as f:
        pubs = json.load(f)
    out = []
    for p in pubs:
        authors = render_authors(p.get("authors", ""))
        title = tex_escape(p["title"])
        venue = tex_escape(p.get("venue", ""))
        year = p.get("year", "")
        tag = f"{venue} {year}".strip()
        url = p.get("links", {}).get("Paper", "")
        link = (
            f"\\href{{{url}}}{{\\textcolor{{link}}{{ [\\textit{{{tag}}}]}}}}"
            if url else f"[\\textit{{{tag}}}]"
        )
        note = contrib_note(p)
        note_tex = f" ({note})" if note else ""
        out.append(
            f"            \\item {authors}. ``{title},'' {link}{note_tex}\n"
            f"            \\vspace{{0.7mm}}"
        )
    print("\n".join(out))


if __name__ == "__main__":
    main()
