#!/usr/bin/env python3
"""
gen_cv_pubs.py - emit the LaTeX Publications block from publications.json.

This is how publications.json drives the CV without a .bib. It prints
\\cvitemize2 items matching the existing resume style:
  - author names abbreviated to "F Last" (Zehao Xiao -> \\textbf{Z Xiao})
  - equal-contribution "*" marks preserved from the JSON author strings
  - a "(Equal contribution)" note auto-emitted when an entry has 2+ "*" marks,
    or a custom note taken from an optional per-entry "contrib" field
    (e.g. "Corresponding author")
  - venue+year as a linked tag

Paste the output into resume/Publications.tex, or have cc splice it between
markers:
    % PUBS-START (auto-generated by gen_cv_pubs.py — do not edit by hand)
    ...generated items...
    % PUBS-END

Usage: python3 gen_cv_pubs.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

ME = "Zehao Xiao"


def tex_escape(s):
    return s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")


# 复合姓(无小写连词,无法用规则判断)的显式覆盖:全名 -> 姓氏部分
COMPOUND_SURNAMES = {
    "Youssef Attia El Hili": "Attia El Hili",
    "Y Attia El Hili": "Attia El Hili",
}
# 姓氏连词:出现即视为姓氏起点(van Noord / de Bruin / von Neumann ...)
PARTICLES = {"van", "von", "de", "den", "der", "di", "da", "del", "la", "le", "dos", "bin"}


def abbrev(name):
    """'Wenzhe Yin*' -> 'W Yin*'; 'Nanne van Noord' -> 'N van Noord';
    'Mohammad Mahdi Derakhshani' -> 'M Derakhshani' (中间名丢弃)."""
    name = name.strip()
    star = ""
    if name.endswith("*"):
        star, name = "*", name[:-1].strip()
    if name in COMPOUND_SURNAMES:
        return f"{name.split()[0][0].upper()} {COMPOUND_SURNAMES[name]}{star}"
    toks = name.split()
    if len(toks) <= 1:
        return name + star
    for i, t in enumerate(toks[1:], start=1):
        if t.lower() in PARTICLES:
            return f"{toks[0][0].upper()} {' '.join(toks[i:])}{star}"
    return f"{toks[0][0].upper()} {toks[-1]}{star}"


def render_authors(authors):
    parts = []
    for a in authors.split(","):
        a = a.strip()
        if not a:
            continue
        short = abbrev(a)
        if a.replace("*", "").strip() == ME:
            short = f"\\textbf{{{short}}}"
        parts.append(short)
    return ", ".join(parts)


def contrib_note(p):
    if p.get("cv_contrib"):
        return p["cv_contrib"]
    if p.get("contrib"):
        return p["contrib"]
    if p.get("authors", "").count("*") >= 2:
        return "Equal contribution"
    return ""


def main():
    with open(os.path.join(HERE, "publications.json"), encoding="utf-8") as f:
        pubs = json.load(f)
    # Keep the homepage order in publications.json; group the generated CV by
    # authorship. Listed-first and equal-first work leads, then Tabby, then the
    # remaining co-authored publications. Python's sort preserves source order
    # inside each group.
    def cv_rank(p):
        names = [name.strip() for name in p.get("authors", "").split(",")]
        if names and names[0].rstrip("*").strip() == ME:
            return 0
        # GO4Align uses a star for corresponding authorship, not equal-first.
        if p.get("contrib") != "Corresponding author" and any(
            name.endswith("*") and name.rstrip("*").strip() == ME for name in names
        ):
            return 1
        if p["title"].startswith("Tabby: An Open Pretraining Recipe"):
            return 2
        return 3

    out = []
    for p in sorted(pubs, key=cv_rank):
        authors = render_authors(p.get("authors", ""))
        title = tex_escape(p["title"])
        venue = tex_escape(p.get("venue", ""))
        year = p.get("year", "")
        tag = f"{venue} {year}".strip()
        url = p.get("links", {}).get("Paper", "")
        link = (
            f"\\href{{{url}}}{{\\textcolor{{link}}{{ [\\textit{{{tag}}}]}}}}"
            if url else f"[\\textit{{{tag}}}]"
        )
        note = contrib_note(p)
        note_tex = f" ({note})" if note else ""
        out.append(
            f"            \\item {authors}. ``{title},'' {link}{note_tex}\n"
            f"            \\vspace{{0.3mm}}"
        )
    print("\n".join(out))


if __name__ == "__main__":
    main()
